export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
